all:
	g++ -o tutorial4 tutorial4.cpp ../evg/openglarea3.cpp ../evg/program.cpp ../evg/shader.cpp -std=c++11  $(shell pkg-config --cflags --libs gtkmm-3.0) $(shell pkg-config --cflags --libs glew) -lX11 -I.. -O3 -pedantic -Wall
